package databaseEntity;
// Generated 4.12.2016 18:50:29 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * SalaryId generated by hbm2java
 */
public class SalaryId implements java.io.Serializable {

	private int personalId;
	private short month;
	private short year;

	public SalaryId() {
	}

	public SalaryId(int personalId, short month, short year) {
		this.personalId = personalId;
		this.month = month;
		this.year = year;
	}

	public int getPersonalId() {
		return this.personalId;
	}

	public void setPersonalId(int personalId) {
		this.personalId = personalId;
	}

	public short getMonth() {
		return this.month;
	}

	public void setMonth(short month) {
		this.month = month;
	}

	public short getYear() {
		return this.year;
	}

	public void setYear(short year) {
		this.year = year;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalaryId))
			return false;
		SalaryId castOther = (SalaryId) other;

		return (this.getPersonalId() == castOther.getPersonalId()) && (this.getMonth() == castOther.getMonth())
				&& (this.getYear() == castOther.getYear());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPersonalId();
		result = 37 * result + this.getMonth();
		result = 37 * result + this.getYear();
		return result;
	}
	
	@Override
	public String toString() {
		return "SalaryId [personalId=" + personalId + ", month=" + month + ", year=" + year + "]";
	}
}
