package databaseEntity;
// Generated 4.12.2016 18:50:29 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Salary generated by hbm2java
 */
public class Salary implements java.io.Serializable, EntityDefinition {

	private SalaryId id;
	private Staffperson staffperson;
	private BigDecimal salarySum;
	private BigDecimal extraSalary;

	public Salary() {
	}

	public Salary(SalaryId id, Staffperson staffperson, BigDecimal salarySum) {
		this.id = id;
		this.staffperson = staffperson;
		this.salarySum = salarySum;
	}

	public Salary(int personalId, short month, short year, BigDecimal salarySum, BigDecimal extraSalary) {
		this.id = new SalaryId(personalId, month, year);
		this.salarySum = salarySum;
		this.extraSalary = extraSalary;
	}
	
	public Salary(SalaryId id, Staffperson staffperson, BigDecimal salarySum, BigDecimal extraSalary) {
		this.id = id;
		this.staffperson = staffperson;
		this.salarySum = salarySum;
		this.extraSalary = extraSalary;
	}

	public SalaryId getId() {
		return this.id;
	}

	public void setId(SalaryId id) {
		this.id = id;
	}

	public Staffperson getStaffperson() {
		return this.staffperson;
	}

	public void setStaffperson(Staffperson staffperson) {
		this.staffperson = staffperson;
	}

	public BigDecimal getSalarySum() {
		return this.salarySum;
	}

	public void setSalarySum(BigDecimal salarySum) {
		this.salarySum = salarySum;
	}

	public BigDecimal getExtraSalary() {
		return this.extraSalary;
	}

	public void setExtraSalary(BigDecimal extraSalary) {
		this.extraSalary = extraSalary;
	}
	
	@Override
	public String toString() {
		return "Salary ["+id.toString()+", staffperson=" + staffperson + ", salarySum=" + salarySum + ", extraSalary="
				+ extraSalary + "]";
	}
	
	public void copyParameters(Salary copySalary){
		this.salarySum = copySalary.getSalarySum();
		this.extraSalary = copySalary.getExtraSalary();
	}

	@Override
	public List<String> tableColumnNames() {
		List<String> outputList = new ArrayList<>();
		
		outputList.add("personalId");
		outputList.add("month");
		outputList.add("year");
		outputList.add("salarySum");
		outputList.add("extraSalary");
				
		return outputList;
	}
}
