package databaseEntity;
// Generated 4.12.2016 18:50:29 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Staffperson generated by hbm2java
 */
public class Staffperson implements java.io.Serializable, EntityDefinition {

	private Integer personalId;
	private String fisrtName;
	private String surname;
	private String city;
	private String postalCode;
	private String street;
	private int houseNumber;
	private String phone;
	private String email;
	private Set salaries = new HashSet(0);

	public Staffperson() {
	}

	public Staffperson(String fisrtName, String surname, String city, String postalCode, String street,
			int houseNumber) {
		this.fisrtName = fisrtName;
		this.surname = surname;
		this.city = city;
		this.postalCode = postalCode;
		this.street = street;
		this.houseNumber = houseNumber;
	}

	public Staffperson(String fisrtName, String surname, String city, String postalCode, String street,
			int houseNumber, String phone, String email) {
		this.fisrtName = fisrtName;
		this.surname = surname;
		this.city = city;
		this.postalCode = postalCode;
		this.street = street;
		this.houseNumber = houseNumber;
		this.phone = phone;
		this.email = email;
	}

	public Staffperson(String fisrtName, String surname, String city, String postalCode, String street, int houseNumber,
			String phone, String email, Set salaries) {
		this.fisrtName = fisrtName;
		this.surname = surname;
		this.city = city;
		this.postalCode = postalCode;
		this.street = street;
		this.houseNumber = houseNumber;
		this.phone = phone;
		this.email = email;
		this.salaries = salaries;
	}

	public Integer getPersonalId() {
		return this.personalId;
	}

	public void setPersonalId(Integer personalId) {
		this.personalId = personalId;
	}

	public String getFisrtName() {
		return this.fisrtName;
	}

	public void setFisrtName(String fisrtName) {
		this.fisrtName = fisrtName;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public int getHouseNumber() {
		return this.houseNumber;
	}

	public void setHouseNumber(int houseNumber) {
		this.houseNumber = houseNumber;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getSalaries() {
		return this.salaries;
	}

	public void setSalaries(Set salaries) {
		this.salaries = salaries;
	}
	
	@Override
	public String toString() {
		return "Staffperson [personalId=" + personalId + ", fisrtName=" + fisrtName + ", surname=" + surname + ", city="
				+ city + ", postalCode=" + postalCode + ", street=" + street + ", houseNumber=" + houseNumber
				+ ", phone=" + phone + ", email=" + email + "]";
	}
	
	public void copyParameters(Staffperson copySource){
		this.fisrtName = copySource.getFisrtName();
		this.surname = copySource.getSurname();
		this.city = copySource.getCity();
		this.postalCode = copySource.getPostalCode();
		this.street = copySource.getStreet();
		this.houseNumber = copySource.getHouseNumber();
		this.phone = copySource.getPhone();
		this.email = copySource.getEmail();
	}

	@Override
	public List<String> tableColumnNames() {
		List<String> outputList = new ArrayList<>();
		
		outputList.add("personalId");
		outputList.add("fisrtName");
		outputList.add("surname");
		outputList.add("city");
		outputList.add("postalCode");
		outputList.add("street");
		outputList.add("houseNumber");
		outputList.add("phone");
		outputList.add("email");
				
		return outputList;
	}
}
